### ISSUE TITLE
Removal of Data.Nat.Properties.Simple in v1.0 of the standard library

### ISSUE THREAD

**Issue by MatthewDaggitt** [metaborg/mj.agda#3]
Hi, this is a ping that the module `Data.Nat.Properties.Simple` will be removed in the upcoming release of v1.0 the standard library. The module has been deprecated since v0.14.

If you wish to continue using the latest version of the standard library you will need to update some of the files:
```
Prelude.agda
```

This can be done by replacing `open import Data.Nat.Properties.Simple` with `open import Data.Nat.Properties`.

**Comment by ajrouvoet** [comment]
What a service! This development is a bit behind already and still uses some additions to the stdlib (also behind) that I'm working on getting in upstream (e.g. monotone predicate monads PR). 

if that is all sorted out, mj.agda will be brought up-to-date again.

**Comment by MatthewDaggitt** [comment]
An additional heads-up that `Relation.Binary.Product` which was deprecated a couple of years back will be removed in the upcoming v1.0 of the standard library. You should use `Data.Product.Relation.Binary.Pointwise` instead.

The following file will need to be changed:
https://github.com/metaborg/mj.agda/blob/master/src/MJ/Classtable/Membership.agda

**Comment by ajrouvoet** [comment]
Fixed with the compatibility release for 2.6.1.1
